import Head from "next/head";

export const Header = () => {
  return (
    <>
      <Head>
        <title>Nueva App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>Hola mundo</h1>
      </header>
    </>
  );
};
